title: Higher Ground SRD 1.0
description: Alpha edition SRD for the Higher Ground TTRPG
theme: just-the-docs

url: https://ajzinni.github.io/HG_SRD

aux_links:
  Template Repository: https://github.com/ajzinni/HG_SRD

# Aux links for the upper right navigation
aux_links:
  "Back to Revivify Games":
    - "https://www.revivifygames.com"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true