title: Higher Ground SRD 1.0
description: Alpha edition SRD for the Higher Ground TTRPG
theme: just-the-docs

url: https://ajzinni.github.io/HG_SRD

aux_links:
  Template Repository: https://github.com/ajzinni/HG_SRD